"""added bio in user model

Revision ID: 7be3a614589f
Revises: 742ad4b81e35
Create Date: 2024-12-11 17:53:57.535995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7be3a614589f"
down_revision: Union[str, None] = "742ad4b81e35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("bio", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "bio")
    # ### end Alembic commands ###
